### ISSUE TITLE
NPE on scanning a maven project

### ISSUE THREAD

**Issue by jensnerche** [buschmais/jqassistant#233] opened 2015-09-03 13:03 UTC
Nothing special, worked already but fails now (nobody knows why)
JDK 1.8.0_40 on Windows 7
Maybe there is some problem in maven config, but a NPE is a programming error and a meaningful exception should be thrown.

[ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:scan (default) on project MyCoolProject: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:scan failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:scan (default) on project MyCoolProject: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:scan failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.0.0:scan failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:266)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:247)
	at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo.doExecute(AbstractModuleMojo.java:16)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by DirkMahler** [comment] 2015-09-03 13:42
Duplicate of #216.

**Closed by DirkMahler** 2015-09-03 13:42 UTC
Labels: duplicate
