### ISSUE TITLE
Schema location wrong ?

### ISSUE THREAD

**Issue by rogergl** [buschmais/jqassistant#267] opened 2015-09-26 15:02 UTC
At least I get a 404 for this:

http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0

**Comment by obfischer** [comment] 2015-09-26 15:34
Is a known issue we will fix with the next release.

**Comment by obfischer** [comment] 2015-09-27 22:52
@DirkMahler can we use for this a subdomain we own? For example schema.jqassistang.org?

**Comment by DirkMahler** [comment] 2015-09-28 14:50
Just clarifying this internally...

**Comment by obfischer** [comment] 2015-10-17 12:00
Is a duplicate of #202. IT will be done for the 1.2.0 release.

**Closed by obfischer** 2015-10-17 12:00 UTC
Labels: bug
