### ISSUE TITLE
NPE while scanning POM file 

### ISSUE THREAD

**Issue by louzadod** [buschmais/jqassistant#287] opened 2015-10-23 11:12 UTC
In the new 1.1.0-RC1, while scanning POM file using $JQASSISTANT_HOME/bin/jqassistant.sh scan :Maven:Artifact:Pom:Xml:File -f file.pom an NPE is thrown.

See stacktrace below.

```java
Exception in thread "main" java.lang.IllegalStateException: Unexpected problem while scanning: item='./merged-maven-repo/repo/com/liferay/maven/plugins/liferay-maven-plugin/6.2.1/liferay-maven-plugin-6.2.1.pom', path='/var/neo4j/mavendb/tmp/./merged-maven-repo/repo/com/liferay/maven/plugins/liferay-maven-plugin/6.2.1/liferay-maven-plugin-6.2.1.pom', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin@10830d50]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:85)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.scan(ScanTask.java:126)
        at com.buschmais.jqassistant.scm.cli.task.ScanTask.executeTask(ScanTask.java:73)
        at com.buschmais.jqassistant.scm.cli.task.AbstractTask.run(AbstractTask.java:61)
        at com.buschmais.jqassistant.scm.cli.Main.executeTask(Main.java:235)
        at com.buschmais.jqassistant.scm.cli.Main.interpretCommandLine(Main.java:187)
        at com.buschmais.jqassistant.scm.cli.Main.run(Main.java:73)
        at com.buschmais.jqassistant.scm.cli.Main.main(Main.java:44)
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: item='com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin$1@19fc0ef7', path='/var/neo4j/mavendb/tmp/./merged-maven-repo/repo/com/liferay/maven/plugins/liferay-maven-plugin/6.2.1/liferay-maven-plugin-6.2.1.pom', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@6de9bba2, com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenPomFileScannerPlugin@16f8df70, com.buschmais.jqassistant.plugin.xml.impl.scanner.XmlFileScannerPlugin@47e725af]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:85)
        at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:50)
        at com.buschmais.jqassistant.plugin.common.impl.scanner.FileScannerPlugin.scan(FileScannerPlugin.java:20)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
        ... 7 more
Caused by: java.lang.IllegalStateException: Unexpected problem while scanning: item='com.liferay.maven.plugins:liferay-maven-plugin:maven-plugin:[inherited]', path='/var/neo4j/mavendb/tmp/./merged-maven-repo/repo/com/liferay/maven/plugins/liferay-maven-plugin/6.2.1/liferay-maven-plugin-6.2.1.pom', scope='NONE', pipeline='[com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin@796cf2b5]'.
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:85)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.AbstractMavenPomScannerPlugin.scan(AbstractMavenPomScannerPlugin.java:61)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.AbstractMavenPomScannerPlugin.scan(AbstractMavenPomScannerPlugin.java:25)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
        ... 10 more
Caused by: java.lang.NullPointerException
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.createMavenPomXmlDescriptor(MavenModelScannerPlugin.java:91)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.scan(MavenModelScannerPlugin.java:57)
        at com.buschmais.jqassistant.plugin.maven3.impl.scanner.MavenModelScannerPlugin.scan(MavenModelScannerPlugin.java:32)
        at com.buschmais.jqassistant.core.scanner.impl.ScannerImpl.scan(ScannerImpl.java:77)
        ... 13 more
```

**Comment by DirkMahler** [comment] 2015-10-23 11:31
This is a duplicate of #272

**Closed by DirkMahler** 2015-10-23 11:31 UTC
Labels: bug, duplicate
