### ISSUE TITLE
Scan failed, because of transaction rolled back

### ISSUE THREAD

**Issue by jdufner** [buschmais/jqassistant#396] opened 2018-08-30 06:00 UTC
I want to scan my project "capability" to analyze it with jQAssistant (com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0). The scan starts, but while it is commiting the following exception raises:

[ERROR] Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:scan (default) on project capability: Execution default of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:scan failed: Transaction was marked as successful, but unable to commit transaction so rolled back.: Transaction rolled back even if marked as successful -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:scan (default) on project capability: Execution default of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:scan failed: Transaction was marked as successful, but unable to commit transaction so rolled back.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.buschmais.jqassistant:jqassistant-maven-plugin:1.4.0:scan failed: Transaction was marked as successful, but unable to commit transaction so rolled back.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:100)
	at com.buschmais.xo.neo4j.embedded.impl.datastore.EmbeddedNeo4jDatastoreTransaction.closeTransaction(EmbeddedNeo4jDatastoreTransaction.java:52)
	at com.buschmais.xo.neo4j.embedded.impl.datastore.EmbeddedNeo4jDatastoreTransaction.commit(EmbeddedNeo4jDatastoreTransaction.java:30)
	at com.buschmais.xo.impl.XOTransactionImpl.commit(XOTransactionImpl.java:38)
	at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.commitTransaction(AbstractGraphStore.java:165)
	at com.buschmais.jqassistant.scm.maven.ScanMojo.execute(ScanMojo.java:98)
	at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo$1.run(AbstractModuleMojo.java:21)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:340)
	at com.buschmais.jqassistant.scm.maven.AbstractModuleMojo.execute(AbstractModuleMojo.java:24)
	at com.buschmais.jqassistant.scm.maven.AbstractMojo.execute(AbstractMojo.java:212)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.neo4j.internal.kernel.api.exceptions.TransactionFailureException: Transaction rolled back even if marked as successful
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.failOnNonExplicitRollbackIfNeeded(KernelTransactionImplementation.java:599)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:541)
	at org.neo4j.internal.kernel.api.Transaction.close(Transaction.java:189)
	at org.neo4j.kernel.impl.coreapi.TopLevelTransaction.close(TopLevelTransaction.java:78)
	... 31 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[INFO] Closing store in directory 'file:/Users/jndufner/git-workspaces/scs/payment-capability/target/jqassistant/store'.
[WARNING] Rolling back an active transaction.

I already set the memory setting:
export JQASSISTANT_OPTS=-Xmx1024M
export MAVEN_OPTS=-Xmx1024M

**Comment by jdufner** [comment] 2018-08-30 06:01
I you want, I will send you the complete Maven debug output.

**Comment by jdufner** [comment] 2018-08-30 06:02
[jqassistant_maven_debug_log.txt](https://github.com/buschmais/jqassistant/files/2334778/jqassistant_maven_debug_log.txt)

**Comment by obfischer** [comment] 2018-09-01 20:25
Same problem as buschmais/jqa-maven-plugin#17.

**Comment by DirkMahler** [comment] 2018-09-03 15:04
Maybe we have a similar issue with error handling but in the case still the root cause is unclear. Would need to analyze the last scanned file to see if any error is thrown there that cannot be handled correctly.

**Comment by obfischer** [comment] 2018-09-04 09:14
IMHO this issues refers to the general error handling in jQA. Even if the root cause is unclear, we must ensure that jQA is usable by the enduser. In my case I can't use jQA in some of my projects because of that. Even if I am not interessted in the scaned artifact that caused the problem.

Nethertheless we must be also able to identify the root case.

BTW, we have the `continueOnError` parameter. If this parameter is set to true we **must** ensure that the enduser can use the scanning result.

**Comment by DirkMahler** [comment] 2018-10-02 10:40
Just as clarification: The scanning result by definition will be inconsistent, so we cannot give any guarantee. We only offer the user an option to continue on his own risk.

**Comment by DirkMahler** [comment] 2018-10-17 07:57
Close this issue right now as the known issue has been fixed for 1.5 and it has been a corner case as well that was not yet covered by the exception handling. Any other corner cases should end up in new issues.

**Closed by DirkMahler** 2018-10-17 07:57 UTC
Labels: bug, in progress
