### ISSUE TITLE
severity not correctly handled

### ISSUE THREAD

**Issue by aklemp** [buschmais/jqassistant#314] opened 2015-12-03 13:27 UTC
Hi,

the severity is not correctly handled in logging. For testing purposes, I used the Java concepts, all with severity MINOR, referenced one as CRITICAL and one as INFO. Then I set the severity in Maven to MAJOR. I would expect, that only the CRITICAL concept failing stops the build.

Firstly, the following is logged correctly.
```
[INFO] Applying concept 'java:Error' with severity: 'INFO (from MINOR)'.
[INFO] Applying concept 'java:Throwable' with severity: 'MINOR'.
[INFO] Applying concept 'java:RuntimeException' with severity: 'MINOR'.
[INFO] Applying concept 'java:Exception' with severity: 'CRITICAL (from MINOR)'.
```

Lastly, the following is logged correctly, because only one concept fails.
```
[ERROR] Failed to execute goal com.buschmais.jqassistant.scm:jqassistant-maven-plugin:1.1.0:analyze (default) on project xyz: Violations detected: 1 concepts, 0 constraints -> [Help 1]
```

But in between the logging is incorrect and thus I have no easy information which is the failing concept. All failing concepts are logged as error with severity MINOR.

```
[ERROR] --[ Concept Application Failure ]----------------------------------
[ERROR] Concept: java:Error
[ERROR] Severity: MINOR
[ERROR] Labels types deriving from java.lang.Error as "Error".
[ERROR] -------------------------------------------------------------------
[ERROR]

[ERROR] --[ Concept Application Failure ]----------------------------------
[ERROR] Concept: java:Exception
[ERROR] Severity: MINOR
[ERROR] Labels types deriving from java.lang.Exception as "Exception".
[ERROR] -------------------------------------------------------------------
[ERROR]

[ERROR] --[ Concept Application Failure ]----------------------------------
[ERROR] Concept: java:RuntimeException
[ERROR] Severity: MINOR
[ERROR] Labels types deriving from java.lang.RuntimeException as "RuntimeException".
[ERROR] -------------------------------------------------------------------
[ERROR]

[ERROR] --[ Concept Application Failure ]----------------------------------
[ERROR] Concept: java:Throwable
[ERROR] Severity: MINOR
[ERROR] Labels types deriving from java.lang.Throwable as "Throwable".
[ERROR] -------------------------------------------------------------------
[ERROR]
```

Three of them are definitely no errors, because I configured the severity, that these concepts are not that important to me. The effective severity is not correct for two of them. However, I'm not sure, if logging them as WARNING is useful with seven lines each. Maybe only a short notice like

```
[WARNING] Concept 'java:Throwable' with severity MINOR didn't match anything.
```

Kind regards,
  aklemp

**Comment by obfischer** [comment] 2015-12-03 13:38
I would like to schedule it for 1.2.0. WDYT?

**Comment by obfischer** [comment] 2015-12-03 13:40
It is an error from the view point of Maven. Currently a failed concept is logged as error. The severity is currently not taken in consideration.

**Comment by DirkMahler** [comment] 2015-12-03 13:49
As far as I understand the problem is not the severity of the Maven logger but:

```
Applying concept 'java:Exception' with severity: 'CRITICAL (from MINOR)'.
```

vs.

```
--[ Concept Application Failure ]----------------------------------
Concept: java:Exception
Severity: MINOR
Labels types deriving from java.lang.Exception as "Exception".
-------------------------------------------------------------------
```
(should be critical here). So it's a bug and should be fixed in 1.1.1

**Comment by DirkMahler** [comment] 2015-12-03 18:00
@aklemp The different severities messages have been fixed - would this be ok for closing the ticket?

**Comment by obfischer** [comment] 2015-12-03 19:02
Now I got it...

**Comment by aklemp** [comment] 2015-12-04 11:49
Can I get the latest build from Travis-CI somewhere for testing?

**Comment by DirkMahler** [comment] 2015-12-04 11:53
The latest snapshots are uploaded to https://oss.sonatype.org/content/repositories/snapshots/, you should use 1.1.1-SNAPSHOT

**Comment by aklemp** [comment] 2015-12-04 14:46
The severity is now shown correctly `CRITICAL (from MINOR)` but it is still logged as error by Maven. Currently, I have a few pages of failing concepts in the Maven log as errors, but all except one have severity MINOR and thus are not the cause. I have to manually check for the failing concepts with a high enough severity (and have to check the Maven configuration first, if I can't remember the minimum severity).

**Comment by obfischer** [comment] 2015-12-04 14:51
Yes, we should adapt the logging level used by reporter should reflect the effictive severity.

**Comment by DirkMahler** [comment] 2015-12-04 15:39
Hm, what does this mean?

- use a log level that corresponds to the severity which has been used to execute a rule
- use error for all rules that would break the build and info or warn for the others?

**Comment by aklemp** [comment] 2015-12-04 15:44
I would prefer the latter: use error for all failing rules that are shown in the summary `Violations detected: X concepts, Y constraints` and info or warn for the others. But also less information for warn/info because 7 lines per failing rule is too much and hides the important information.

**Comment by obfischer** [comment] 2015-12-30 16:49
Can I merge the changes made for this issue to _master_? I would like to merge my changes for #333 too.

**Comment by DirkMahler** [comment] 2015-12-30 17:04
Of course :-) Happy merge and happy new year!

**Closed** 2016-01-13 07:30 UTC
Labels: bug
